services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: netflix_app
    volumes:
      - ./appli_back:/var/www/html
    depends_on:
      - db
      - rabbitmq
    networks:
      - symfony

  nginx:
    image: nginx:alpine
    container_name: nginx_symfony
    ports:
      - "8080:80"
    volumes:
      - ./appli_back:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony

  db:
    image: postgres:15
    container_name: postgres_symfony
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db_data:/var/lib/postgresql/data
    networks:
      - symfony

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./docker/rabbitmq_data:/var/lib/rabbitmq
    networks:
      - symfony

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - symfony

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - ./docker/jenkins_data:/var/jenkins_home
    networks:
      - symfony

volumes:
  db_data:
  jenkins_data:
  rabbitmq_data:

networks:
  symfony:
